FROM golang:1.22 AS src

WORKDIR /api

# Copy dependencies first to take advantage of Docker caching
COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /fukubox-api
CMD ["/fukubox-api"]
EXPOSE 3000